DotNetFrameworkRefresh/Models/Service.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DotNetFrameworkRefresh.Models
{
    [Table("services")]
    public class Service
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public int? CarId { get; set; }
        public virtual Car Car { get; set; }

        [Required]
        [Display(Name = "Service Date & Time")]
        public DateTime? ServiceDateTime { get; set; }

        [Required]
        [Display(Name = "Service Duration (hours)")]
        [DisplayFormat(DataFormatString = "{0:N2}", ApplyFormatInEditMode = true)]
        public decimal? ServiceHours { get; set; }

        [Required]
        [Display(Name = "Service Notes")]
        public string ServiceNotes { get; set; }


    }
}

DotNetFrameworkRefresh/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DotNetFrameworkRefresh.Data;
using DotNetFrameworkRefresh.Models;

namespace DotNetFrameworkRefresh.Controllers
{
    public class ServicesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Services
        public async Task<ActionResult> Index()
        {
            var services = db.Services.Include(s => s.Car);
            return View(await services.ToListAsync());
        }

        // GET: Services/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // GET: Services/Create
        public async Task<ActionResult> Create(int? carId)
        {
            if(!carId.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var car = await db.Cars.FindAsync(carId);

            if(car == null)
            {
                return HttpNotFound();
            }

            return View(new Service() { CarId = car.Id, Car = car });
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,CarId,ServiceDateTime,ServiceHours,ServiceNotes")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Services.Add(service);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Cars", new { id = service.CarId });
            }

            if (!service.CarId.HasValue)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var car = await db.Cars.FindAsync(service.CarId);

            if (car == null)
            {
                return HttpNotFound();
            }

            service.Car = car;

            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            ViewBag.CarId = new SelectList(db.Cars, "Id", "IdentificationNumber", service.CarId);
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,CarId,ServiceDateTime,ServiceHours,ServiceNotes")] Service service)
        {
            if (ModelState.IsValid)
            {
                db.Entry(service).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Details", "Cars", new { id = service.CarId });
            }
            ViewBag.CarId = new SelectList(db.Cars, "Id", "IdentificationNumber", service.CarId);
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = await db.Services.FindAsync(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Service service = await db.Services.FindAsync(id);

            if(service == null)
            {
                return HttpNotFound();
            }

            var carId = service.CarId;

            db.Services.Remove(service);
            await db.SaveChangesAsync();
            return RedirectToAction("Details", "Cars", new { id = carId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DotNetFrameworkRefresh/Views/Services/Create.cshtml
@model DotNetFrameworkRefresh.Models.Service

@{
    ViewBag.Title = "Add Service Entry";
}

<h2>@ViewBag.Title</h2>
<h4 class="text-muted">@Model.Car.IdentificationNumber</h4>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.CarId)

    <div class="form-horizontal">
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.ServiceDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ServiceNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Vehicle", "Details", "Cars", new { Id = Model.CarId }, null)
</div>

DotNetFrameworkRefresh/Views/Services/Delete.cshtml
@model DotNetFrameworkRefresh.Models.Service

@{
    ViewBag.Title = "Delete Service Entry";
}

<h2>@ViewBag.Title</h2>
<h4 class="text-muted">@Model.Car.IdentificationNumber</h4>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Car.Make)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.Make)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceNotes)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to Entry", "Details", "Services", new { Id = Model.Id }, null) |
            @Html.ActionLink("Back to Vehicle", "Details", "Cars", new { Id = Model.CarId }, null)
        </div>
    }
</div>

DotNetFrameworkRefresh/Views/Services/Details.cshtml
@model DotNetFrameworkRefresh.Models.Service

@{
    ViewBag.Title = "Vehicle Service Entry";
}

<h2>@ViewBag.Title</h2>
<h4 class="text-muted">@Model.Car.IdentificationNumber</h4>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Car.IdentificationNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Car.IdentificationNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceHours)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceHours)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ServiceNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ServiceNotes)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to Vehicle", "Details", "Cars", new { Id = Model.CarId }, null)
</p>

DotNetFrameworkRefresh/Views/Services/Edit.cshtml
@model DotNetFrameworkRefresh.Models.Service

@{
    ViewBag.Title = "Edit Service Entry";
}

<h2>@ViewBag.Title</h2>
<h4 class="text-muted">@Model.Car.IdentificationNumber</h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Car.IdentificationNumber, "Car VIN Number", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CarId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CarId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceDateTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceDateTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceDateTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceHours, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceHours, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceHours, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.ServiceNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Entry", "Details", new { Id = Model.Id }) |
    @Html.ActionLink("Back to Vehicle", "Details", "Cars", new { Id = Model.CarId }, null)
</div>